"data":
  "name": "AmericanExpr"
  "batch_size": 128
"learning_rate": 3.25e-4
"model":
  "encoder": "RecurrentVecEncoder"
  "hidden_size": 200
  "rnn": "gru" # gru, lstm
  "num_layers": 2
  "hidden_state_size": 222

# Not used atm
"epochs": -1
"batch_size": -1