"data":
  "name": "AmericanExpr"
"epochs": 100 # -1 epochs means that the whole data will be used for training
"batch_size": 128
"learning_rate": 3.25e-4
"model":
  "encoder": "RecurrentVecEncoder"
  "hidden_size": 200
  "rnn": "gru" # gru, lstm
  "num_layers": 4
  "hidden_state_size": 228