"data":
  "name": "AmericanExpr"
"updates": -1 # -1 updates means that the whole data will be used for training
"batch_size": 256
"learning_rate": 3.25e-4
"save_iter": 10 # Save the model every update % save_iter == 0
"model":
  "encoder": "RecurrentVecEncoder"
  "hidden_size": 512
  "rnn": "gru" # gru, lstm
  "num_layers": 4
  "hidden_state_size": 256