"data":
  "name": "NegativeSeqGen"
  "sequence_len": 3
"updates": 100
"learning_rate": 3.25e-4
"batch_size": 128
"save_iter": 1000
"model":
  "encoder": "RecurrentVecEncoder"
  "hidden_size": 200
  "rnn": "gru" # gru, lstm
  "num_layers": 2
  "hidden_state_size": 222